apiVersion: v1
kind: Service
metadata:
  name: "currexx-extlb"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: "currexx-core"
---
apiVersion: v1
kind: Service
metadata:
  name: "currexx"
spec:
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    app: "currexx-core"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "currexx-core"
  labels:
    app: "currexx-core"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "currexx-core"
  template:
    metadata:
      labels:
        app: "currexx-core"
    spec:
      containers:
        - name: "core"
          image: "kirill1/currexx-core:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          envFrom:
            - secretRef:
                name: "currexx-secret"
          resources:
            requests:
              memory: "192Mi"
              cpu: "0.05"
            limits:
              memory: "320Mi"
              cpu: "0.1"
          readinessProbe:
            httpGet:
              path: /health/status
              port: 8080
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health/status
              port: 8080
            periodSeconds: 600