addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.8.1")
addSbtPlugin("com.lightbend.sbt" % "sbt-javaagent"       % "0.1.6")
addSbtPlugin("org.typelevel"     % "sbt-tpolecat"        % "0.5.2")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.5")
addSbtPlugin("com.github.sbt"    % "sbt-github-actions"  % "0.27.0")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"         % "0.6.4")
