addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.8.1")
addSbtPlugin("com.lightbend.sbt"         % "sbt-javaagent"       % "0.1.6")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.2.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("com.codecommit"            % "sbt-github-actions"  % "0.14.2")
